#' Example SQUID DU Table
#'
#' Example dataset for SQUID DU analysis.
#'
#' @format A data frame with 387 rows and 28 columns:
#' \describe{
#'   \item{PRJ_NAME}{Project name}
#'   \item{WATER_NAME}{Waterbody name}
#'   \item{WATER_ID}{Waterbody identifier}
#'   \item{STATION_NAME}{Monitoring station name}
#'   \item{STATION}{Monitoring station code}
#'   \item{TN_SITE_CLASS}{Total nitrogen site classification}
#'   \item{TP_SITE_CLASS}{Total phosphorus site classification}
#'   \item{ECOREGION}{Ecoregion classification}
#'   \item{ELEVATION}{Elevation in meters}
#'   \item{DU}{Designated use category}
#'   \item{WBODY}{Waterbody type}
#'   \item{WQS_REFERENCE}{Reference to water quality standards}
#'   \item{ECOLI_GEOMEAN}{E. coli geometric mean value}
#'   \item{ECOLI_SINGLE}{Single sample E. coli value}
#'   \item{TEMP_6T3}{Temperature statistic (6T3)}
#'   \item{TEMP_4T3}{Temperature statistic (4T3)}
#'   \item{TEMP_WQC}{Temperature water quality criterion}
#'   \item{PH_LOW}{Lower pH threshold}
#'   \item{PH_HIGH}{Upper pH threshold}
#'   \item{DO_WQC}{Dissolved oxygen water quality criterion}
#'   \item{SC_WQC}{Specific conductance water quality criterion}
#'   \item{TP_WQC}{Total phosphorus water quality criterion}
#'   \item{TDS_WQC}{Total dissolved solids water quality criterion}
#'   \item{SO4_WQC}{Sulfate water quality criterion}
#'   \item{CHL_WQC}{Chlorophyll water quality criterion}
#'   \item{NMAC_NOTES}{Notes from NMAC}
#'   \item{MLOC_UID}{Monitoring location unique identifier}
#'   \item{PRJ_UID}{Project unique identifier}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_SQUID_DU_table"

#' Example SQUID LTD Table
#'
#' Example dataset for SQUID long-term deployment analysis.
#'
#' @format A data frame with 559 rows and 51 columns:
#' \describe{
#'   \item{ASSESSMENT_UNIT_ID}{Assessment unit identifier}
#'   \item{ASSESSMENT_UNIT_NAME}{Assessment unit name}
#'   \item{AQUATIC_LIFE}{Aquatic life use category}
#'   \item{PROJECT_NAME}{Project name}
#'   \item{STATION_ID}{Station identifier}
#'   \item{STATION_NAME}{Station name}
#'   \item{SAMPLING_EVENT_TYPE}{Type of sampling event}
#'   \item{COMMENTS}{General comments}
#'   \item{SE_STAFF}{Sampling event staff}
#'   \item{DATA_LOGGER_NAME}{Name of data logger}
#'   \item{DATA_LOGGER_TYPE}{Type of data logger}
#'   \item{DATA_LOGGER_NO}{Data logger serial number}
#'   \item{ACT_ID}{Activity identifier}
#'   \item{ACTII_ID}{Secondary activity identifier}
#'   \item{ACT_START_DATE}{Activity start date}
#'   \item{ACT_END_DATE}{Activity end date}
#'   \item{DAYS_DEPLOYED}{Number of days deployed}
#'   \item{ACTIVITY_TYPE}{Type of activity}
#'   \item{ACMED_NAME}{Measurement name}
#'   \item{ACTIVITY_COMMENTS}{Comments on activity}
#'   \item{CHARACTERISTIC_NAME}{Characteristic measured}
#'   \item{MEASUREMENT}{Measurement value}
#'   \item{UNITS}{Units of measurement}
#'   \item{WQS_REFERENCE}{Water quality standards reference}
#'   \item{\code{> 3 days deployed}}{Indicator if deployed > 3 days}
#'   \item{ASSESSABILITY_QUALIFIER_CODE}{Assessability qualifier code}
#'   \item{DO_WQC}{Dissolved oxygen criterion}
#'   \item{\code{DO Min < DO WQS?}}{Flag if DO minimum < WQS}
#'   \item{PH_LOW}{Lower pH threshold}
#'   \item{\code{pH Min < pH Low?}}{Flag if pH minimum < low threshold}
#'   \item{PH_HIGH}{Upper pH threshold}
#'   \item{\code{pH Max > pH High?}}{Flag if pH maximum > high threshold}
#'   \item{\code{pH Max > 9.5?}}{Flag if pH maximum > 9.5}
#'   \item{TEMP_WQC}{Temperature criterion}
#'   \item{\code{Temp Max > Temp WQC?}}{Flag if temperature exceeds WQC}
#'   \item{SC_WQC}{Specific conductance criterion}
#'   \item{\code{Max SC > SC WQC?}}{Flag if SC exceeds WQC}
#'   \item{\code{Turbidity Max > 7?}}{Flag if turbidity exceeds 7 NTU}
#'   \item{Turbdity Thresholds}{Turbidity thresholds applied}
#'   \item{Turbidity Threshold Exceeded?}{Flag if turbidity threshold exceeded}
#'   \item{NMAC_NOTES}{Notes from NMAC review}
#'   \item{RES_COMMENTS}{Result comments}
#'   \item{CHR_UID}{Characteristic unique ID}
#'   \item{SE_TYPE_UID}{Sampling event type ID}
#'   \item{RES_UID}{Result unique ID}
#'   \item{ACT_UID}{Activity unique ID}
#'   \item{ACTYP_UID}{Activity type unique ID}
#'   \item{SE_UID}{Sampling event unique ID}
#'   \item{MLOC_UID}{Monitoring location unique ID}
#'   \item{PRJ_UID}{Project unique ID}
#'   \item{AU_UID}{Assessment unit unique ID}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_SQUID_LTD_table"

#' Example SQUID Lake Profile Table
#'
#' Example dataset for SQUID lake profile analysis.
#'
#' @format A data frame with 1925 rows and 14 columns:
#' \describe{
#'   \item{PROJECT_NAME}{Project name}
#'   \item{WATER_ID}{Waterbody identifier}
#'   \item{MLOC_NAME}{Monitoring location name}
#'   \item{MLOC_ID}{Monitoring location ID}
#'   \item{ACT_ID}{Activity identifier}
#'   \item{RES_DEPTH_HEIGHT}{Depth or height of measurement}
#'   \item{CHARACTERISTIC}{Characteristic measured}
#'   \item{MEASUREMENT}{Measurement value}
#'   \item{UNITS}{Units of measurement}
#'   \item{SE_START_DATE_TIME}{Sampling event start date/time}
#'   \item{SWQB_QUALIFIER_CODE}{Qualifier code for SWQB}
#'   \item{RES_COMMENTS}{Result comments}
#'   \item{PRJ_UID}{Project unique ID}
#'   \item{MLOC_UID}{Monitoring location unique ID}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_SQUID_LakeProfile_table"

#' Example SQUID RStudio Table
#'
#' Example dataset for SQUID RStudio integration.
#'
#' @format A data frame with 6443 rows and 47 columns:
#' \describe{
#'   \item{WATER_ID}{Waterbody identifier}
#'   \item{WATER_NAME}{Waterbody name}
#'   \item{PROJECT_NAME}{Project name}
#'   \item{PROJECT_VERIFIED}{Indicator if project verified}
#'   \item{STATION}{Station code}
#'   \item{STATION_NAME}{Station name}
#'   \item{SAMPLING_EVENT_TYPE}{Type of sampling event}
#'   \item{FIELD_STAFF}{Field staff name}
#'   \item{ACT_ID}{Activity identifier}
#'   \item{DATE}{Date of activity}
#'   \item{TIME}{Time of activity}
#'   \item{ACTIVITY_TYPE}{Type of activity}
#'   \item{SAMPLE_TYPE}{Type of sample}
#'   \item{ANALYTE_SUITE}{Analyte suite name}
#'   \item{FLT_10UG}{Filter threshold indicator}
#'   \item{SAMPLE_FRACTION}{Sample fraction type}
#'   \item{CHR_UID}{Characteristic unique ID}
#'   \item{CHARACTERISTIC_NAME}{Characteristic name}
#'   \item{MEASUREMENT}{Measurement value}
#'   \item{UNITS}{Units of measurement}
#'   \item{SDL}{Sample detection limit}
#'   \item{PQL}{Practical quantitation limit}
#'   \item{MDL}{Method detection limit}
#'   \item{MRL}{Minimum reporting level}
#'   \item{SIGMA}{Standard deviation estimate}
#'   \item{LESS_THAN_YN}{Flag if less than detection}
#'   \item{GREATER_THAN_YN}{Flag if greater than threshold}
#'   \item{ANLMTH_ID}{Analysis method ID}
#'   \item{DILUTION_FACTOR}{Dilution factor applied}
#'   \item{LAB_ID}{Laboratory identifier}
#'   \item{ANALYSIS_DATE}{Date of analysis}
#'   \item{WQX_QUALIFIER_CODE}{Qualifier code for WQX}
#'   \item{LAB_QUALIFIER_CODE}{Laboratory qualifier code}
#'   \item{SWQB_QUALIFIER_CODE}{SWQB qualifier code}
#'   \item{RES_COMMENTS}{Result comments}
#'   \item{ACTIVITY_COMMENTS}{Activity comments}
#'   \item{COMMENTS}{General comments}
#'   \item{CHR_CAS_NO}{CAS number for characteristic}
#'   \item{ATTAINS_ID}{ATTAINS identifier}
#'   \item{SE_TYPE_UID}{Sampling event type ID}
#'   \item{RES_UID}{Result unique ID}
#'   \item{ACT_UID}{Activity unique ID}
#'   \item{ACTYP_UID}{Activity type unique ID}
#'   \item{SE_UID}{Sampling event unique ID}
#'   \item{MLOC_UID}{Monitoring location unique ID}
#'   \item{PRJ_UID}{Project unique ID}
#'   \item{AU_UID}{Assessment unit unique ID}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_SQUID_RStudio_table"

#' Example Criteria Table
#'
#' Example dataset containing criteria for SQUID analysis.
#'
#' @format A data frame with 1042 rows and 28 columns:
#' \describe{
#'   \item{CHR_UID}{Characteristic unique ID}
#'   \item{CHR_NAME}{Characteristic name}
#'   \item{CAS}{CAS number}
#'   \item{FRACTION}{Fraction type}
#'   \item{DU}{Designated use}
#'   \item{WBODY}{Waterbody type}
#'   \item{WGROUP}{Waterbody group}
#'   \item{ECOLI_SINGLE}{Single sample E. coli criterion}
#'   \item{SC_WQC}{Specific conductance criterion}
#'   \item{TEMP_WQC}{Temperature criterion}
#'   \item{LT}{Less than threshold indicator}
#'   \item{GT}{Greater than threshold indicator}
#'   \item{HD_METAL}{Hardness dependent metal indicator}
#'   \item{TOXIC}{Toxicity indicator}
#'   \item{TURBAP}{Turbidity applicability}
#'   \item{DWS}{Drinking water supply indicator}
#'   \item{IRR}{Irrigation indicator}
#'   \item{LW}{Livestock watering indicator}
#'   \item{WH}{Wildlife habitat indicator}
#'   \item{ACUTE}{Acute toxicity criterion}
#'   \item{CHRONIC}{Chronic toxicity criterion}
#'   \item{HH}{Human health criterion}
#'   \item{PERSISTENT}{Persistence indicator}
#'   \item{UNITS}{Units of measurement}
#'   \item{ATTAINS CAUSE_GROUP_NAME}{ATTAINS cause group name}
#'   \item{ATTAINS CAUSE_ID}{ATTAINS cause identifier}
#'   \item{ADB_CAUSE_NO}{ADB cause number}
#'   \item{Comments (SCB)}{Comments from SCB}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_criteria_table"

#' Example Parameter Table
#'
#' Example dataset containing parameters for SQUID analysis.
#'
#' @format A data frame with 133 rows and 17 columns:
#' \describe{
#'   \item{CHR_UID}{Characteristic unique ID}
#'   \item{CHR_NAME}{Characteristic name}
#'   \item{WQS_NAME}{Water quality standard name}
#'   \item{SortOrder}{Sort order for display}
#'   \item{ShortName}{Short name for parameter}
#'   \item{ShortNameOLD}{Previous short name}
#'   \item{Units}{Units of measurement}
#'   \item{USE}{Designated use category}
#'   \item{ATTAINS_NAME}{ATTAINS name}
#'   \item{ATTAINs_GROUP_ID}{ATTAINS group identifier}
#'   \item{ATTAINS_GROUP_NAME}{ATTAINS group name}
#'   \item{ATTAINS_ID}{ATTAINS identifier}
#'   \item{ADB_NO}{ADB number}
#'   \item{ADB_NAME}{ADB name}
#'   \item{CAS}{CAS number}
#'   \item{STORET}{STORET code}
#'   \item{SHORT_CAUSE_NAME}{Short cause name}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_parameter_table"

#' Example LANL DU Table
#'
#' Example dataset containing designated use information for LANL sites.
#'
#' @format A data frame with 15 rows and 25 columns:
#' \describe{
#'   \item{PRJ_NAME}{Project name}
#'   \item{WATER_NAME}{Waterbody name}
#'   \item{WATER_ID}{Waterbody identifier}
#'   \item{STATION_NAME}{Monitoring station name}
#'   \item{STATION}{Monitoring station code}
#'   \item{DU}{Designated use category}
#'   \item{WGROUP}{Waterbody group}
#'   \item{WBODY}{Waterbody type}
#'   \item{WQS_REFERENCE}{Reference to water quality standards}
#'   \item{ECOLI_GEOMEAN}{E. coli geometric mean value}
#'   \item{ECOLI_SINGLE}{Single sample E. coli value}
#'   \item{TEMP_6T3}{Temperature statistic (6T3)}
#'   \item{TEMP_4T3}{Temperature statistic (4T3)}
#'   \item{TEMP_WQC}{Temperature water quality criterion}
#'   \item{PH_LOW}{Lower pH threshold}
#'   \item{PH_HIGH}{Upper pH threshold}
#'   \item{DO_WQC}{Dissolved oxygen water quality criterion}
#'   \item{SC_WQC}{Specific conductance water quality criterion}
#'   \item{TP_WQC}{Total phosphorus water quality criterion}
#'   \item{TDS_WQC}{Total dissolved solids water quality criterion}
#'   \item{SO4_WQC}{Sulfate water quality criterion}
#'   \item{CHL_WQC}{Chlorophyll water quality criterion}
#'   \item{NMAC_NOTES}{Notes from NMAC}
#'   \item{MLOC_UID}{Monitoring location unique identifier}
#'   \item{PRJ_UID}{Project unique identifier}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_LANL_DU_table"

#' Example LANL WQ Table
#'
#' Example dataset containing LANL collected water quality data.
#'
#' @format A data frame with 15 rows and 900 columns:
#' \describe{
#'   \item{AU ID}{Unique identifier for the Assessment Unit}
#'   \item{AU / Waterbody Name}{Name of the waterbody or AU}
#'   \item{Submitter / Data Source}{Organization or individual that submitted the data}
#'   \item{Station ID}{Unique identifier for the monitoring station}
#'   \item{Station Name}{Descriptive name of the monitoring station}
#'   \item{Sample Date and Time}{Date and time when the sample was collected}
#'   \item{Sample Media}{Type of sample collected}
#'   \item{Sample Fraction}{Portion of the sample analyzed}
#'   \item{Parameter Name}{Name of the analyte}
#'   \item{Reported Value}{Numeric result of the analysis}
#'   \item{Unit}{Measurement unit for the reported value}
#'   \item{Sample Detection Limit (SDL)}{Minimum concentration that can be reliably detected by the analytical method}
#'   \item{SDL Units}{Units associated with the detection limit}
#'   \item{Less than detection limit?}{Indicator if the result is below the detection limit}
#'   \item{Analytical Method}{Method or procedure used for analysis}
#'   \item{Dilution Factor}{Factor by which the sample was diluted prior to analysis}
#'   \item{Lab Name}{Name of the laboratory that performed the analysis}
#'   \item{Analysis Date and Time}{Date and time when the analysis was completed}
#'   \item{Lab Qualifier Code}{Laboratory-provided qualifier indicating data quality or conditions}
#'   \item{Submitter Qualifier Code}{Submitter-provided qualifier for additional context or data quality notes}
#'   \item{SSWQC Copper Acute (µg/L)}{State Surface Water Quality Criterion for acute copper toxicity}
#'   \item{SSWQC Copper Chronic (µg/L)}{State Surface Water Quality Criterion for chronic copper toxicity}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_LANL_WQ_table"


#' Example Chemistry Processed Table
#'
#' Example dataset of processed chemistry results for water quality analysis.
#'
#' @format A data frame with 5,137 rows and 21 columns:
#' \describe{
#'   \item{WATER_ID}{Assessment Unit identifier}
#'   \item{WATER_NAME}{Assessment Unit name}
#'   \item{PROJECT_NAME}{Project name}
#'   \item{STATION}{Monitoring station code}
#'   \item{STATION_NAME}{Monitoring station name}
#'   \item{SAMPLING_EVENT_TYPE}{Type of sampling event}
#'   \item{DATE}{Date of sample collection}
#'   \item{TIME}{Time of sample collection}
#'   \item{ACTIVITY_TYPE}{Type of activity performed}
#'   \item{SAMPLE_TYPE}{Type of sample collected}
#'   \item{FLT_10UG}{Filter size indicator (10 µg)}
#'   \item{SAMPLE_FRACTION}{Fraction of sample analyzed (e.g., dissolved, total)}
#'   \item{CHR_UID}{Characteristic unique identifier}
#'   \item{CHARACTERISTIC_NAME}{Name of measured characteristic (e.g., nitrate, pH)}
#'   \item{MEASUREMENT}{Reported measurement value (as text)}
#'   \item{MEASUREMENT_num}{Numeric measurement value}
#'   \item{UNITS}{Units of measurement}
#'   \item{LESS_THAN_YN}{Indicator if value is less than detection limit (Y/N)}
#'   \item{ASSESSABILITY_QUALIFIER_CODE}{Qualifier for assessability}
#'   \item{ACT_START_DATE}{Activity start date}
#'   \item{ACT_END_DATE}{Activity end date}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_chemistry_processed"


#' Example Designated Use (DU) Processed Table
#'
#' Example dataset of processed designated use criteria for waterbodies.
#'
#' @format A data frame with 422 rows and 11 columns:
#' \describe{
#'   \item{WATER_ID}{Assessment Unit identifier}
#'   \item{DU}{Designated use category}
#'   \item{Waterbody}{Waterbody type}
#'   \item{TN_SITE_CLASS}{Total nitrogen site classification}
#'   \item{TP_SITE_CLASS}{Total phosphorus site classification}
#'   \item{ECOREGION}{Ecoregion classification}
#'   \item{ELEVATION}{Elevation in feet}
#'   \item{Criteria_Name}{Name of water quality criterion}
#'   \item{Criteria_Value}{Numeric value of the criterion}
#'   \item{CHR_UID}{Characteristic unique identifier}
#'   \item{CHR_UID_Unique}{Unique identifier for characteristic and criterion combination}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_DU_processed"


#' Example Criteria Processed Table
#'
#' Example dataset of processed water quality criteria linked to designated uses and characteristics.
#'
#' @format A data frame with 1,321 rows and 12 columns:
#' \describe{
#'   \item{CHR_UID}{Characteristic unique identifier}
#'   \item{CHR_NAME}{Name of the characteristic (e.g., nitrate, temperature)}
#'   \item{FRACTION}{Sample fraction (e.g., dissolved, total)}
#'   \item{DU}{Designated use category}
#'   \item{Waterbody}{Waterbody qualifier}
#'   \item{PERSISTENT}{Indicator if characteristic is persistent (Y/N)}
#'   \item{HD_METAL}{Indicator if characteristic is a heavy metal (Y/N)}
#'   \item{TOXIC}{Indicator if characteristic is toxic (Y/N)}
#'   \item{TURBAP}{Indicator for turbidity applicability (Y/N)}
#'   \item{UNITS}{Units of measurement for the criterion}
#'   \item{Criteria_Type}{Type of criterion (e.g., chronic, acute)}
#'   \item{Magnitude_Numeric}{Numeric magnitude of the criterion}
#' }
#' @source Generated by \code{Load_Example_Files()} in \code{data-raw}.
"example_criteria_processed"


